### ISSUE TITLE
Bug on setting date on Time Period calendar

### ISSUE THREAD

**Issue by smartm0use** [GIScience/oshdb#163] opened 2019-04-21 22:31 UTC
**Describe the bug**
In the Time Period box, the calendar does not allow to set a date after 19th February 2019.

**To Reproduce**
1. Go to https://ohsome.org/apps/dashboard/
2. Try to pick a date greater that 19th February 2019 on the calendar
3. You can't because the next dates are all disabled

**Expected behavior**
I expect to choose any date from the calendar.

**Error messages, logs, screenshots**
[Screenshot](https://i.ibb.co/w7m7FNm/calendar.png)

**Comment by rtroilo** [comment] 2019-04-22 13:01
Hi smartm0use,
thank you for your report and interest in our service.
But actually it is not a bug. The 19th February was the date of the import and to prevent that people query later than the import date, which will return wrong results, the date is limited to the import date.

We will do a new import this week, and setup a regular update of the data. so that the date limit is closer to the current date.

For the post humanitarian crisis after the hurricane idai event in mosambic, we have a dashboard which gets update once per our. see
https://ohsome.org/apps/dashboard-idai/

We will close this report, after the update this week.

**Comment by smartm0use** [comment] 2019-04-22 21:55
I see, thank you for your message.
Keep up the good work ;)

**Comment by rtroilo** [comment] 2019-04-26 12:50
Hi smartmOuse,

we just updated our database. Latest possible query date is now 2019-04-21T23:00:00Z. And we want to update it at least once a week.
Just check the date picker to see how current the data is in our db.

Thank you.

**Closed by rtroilo** 2019-04-26 12:50 UTC
